site_name: Drifter
site_description: Drifter is a framework to help provision developer boxes using Ansible and Vagrant
site_author: Liip SA

repo_name: "Drifter on GitHub"
repo_url: https://github.com/liip/drifter

#requird due to https://github.com/rtfd/readthedocs.org/issues/1313
#see http://mkdocs.readthedocs.org/en/latest/user-guide/styling-your-docs/#customising-a-theme
extra_javascript:
  - assets/extra.js

theme: readthedocs
pages:
  - 'Home': 'index.rst'
  - 'Roles':
    - 'System roles': 'roles/system.rst'
    - 'Webserver roles': 'roles/webservers.rst'
    - 'Database roles': 'roles/databases.rst'
    - 'PHP roles': 'roles/php.rst'
    - 'Python roles': 'roles/python.rst'
    - 'Ruby roles': 'roles/ruby.rst'
    - 'Java roles': 'roles/java.rst'
    - 'Front-end roles': 'roles/frontend.rst'
    - 'Other roles': 'roles/others.rst'
  - 'Tips & Tricks':
    - 'PHP Debugging': 'tips/php.rst'
    - 'Integrating with Gitlab CI': 'tips/ci.rst'
  - 'Roadmap': 'roadmap.rst'
  - 'Custom boxes': 'boxes.rst'
  - 'Migrations': 'migrations.rst'
