- name: Install Firefox dependencies
  apt:
    pkg: "{{ firefox_dependencies }}"
    state: present
  become: yes

- name: Download latest Firefox
  get_url: url={{ firefox_latest_url }} dest=/opt/firefox.tar.bz2
  become: yes
  when: firefox_version == 'latest'

- name: Download Firefox {{ firefox_version }}
  get_url: url={{ firefox_download_url }} dest=/opt/firefox.tar.bz2
  become: yes
  when: firefox_version != 'latest'

- name: Unpack Firefox
  unarchive: src=/opt/firefox.tar.bz2 dest=/opt/ copy=no creates=/opt/firefox/
  become: yes

- name: Create Firefox Symlinks
  file: state=link src=/opt/firefox/firefox path=/usr/local/bin/firefox
  become: yes

- name: Download geckodriver {{ geckodriver_version }}
  get_url: url={{ geckodriver_download_url }} dest=/opt/geckodriver-{{ geckodriver_version }}.tar.gz
  become: yes

- name: Make directory for geckodriver
  file: path=/opt/geckodriver-{{ geckodriver_version }} state=directory
  become: yes

- name: Unpack Geckodriver
  unarchive: src=/opt/geckodriver-{{ geckodriver_version }}.tar.gz dest=/opt/geckodriver-{{ geckodriver_version }}/ copy=no
  become: yes

- name: Create Geckodriver Symlinks
  file: state=link src=/opt/geckodriver-{{ geckodriver_version }}/geckodriver path=/usr/local/bin/geckodriver
  become: yes
