---
- name: install rbenv
  git:
    repo: https://github.com/rbenv/rbenv.git
    dest: ~/.rbenv
    version: v1.1.0

- name: try to compile dynamic bash extension to speed up rbenv
  command: src/configure && make -C src
  ignore_errors: yes
  args:
    chdir: ~/.rbenv/

- name: install ruby-build plugin
  git:
    repo: https://github.com/rbenv/ruby-build.git
    dest: ~/.rbenv/plugins/ruby-build
    version: v20170112

- name: ensure rbenv is accessible
  lineinfile:
    dest: ~/.bashrc
    line: export PATH="$HOME/.rbenv/bin:$PATH"

- name: init rbenv
  lineinfile:
    dest: ~/.bashrc
    line: eval "$(rbenv init -)"

- name: Install ruby {{ ruby_version }}
  command: rbenv install {{ ruby_version }}
  args:
    chdir: ~/.rbenv/bin/
    creates: ~/.rbenv/shims/ruby

- name: Set ruby {{ ruby_version }} globally
  command: rbenv global {{ ruby_version }}
  args:
    chdir: ~/.rbenv/bin/

- name: Disable gem docs
  template:
    src: gem_config.j2
    dest: ~/.gemrc

- name: Install bundler
  command: gem install bundler
  args:
    chdir: ~/.rbenv/shims/

- name: Install Gems from Gemfile if any
  command: bundle install
  args:
    removes: /vagrant/Gemfile
