- name: create directory for composer
  become: yes
  file: name={{ composer.dir }} state=directory

- command: test -f {{ composer.dir }}/composer.phar
  register: composer_installed
  ignore_errors: yes

- name: install composer
  become: yes
  shell: "cd {{ composer.dir }} && curl -sS https://getcomposer.org/installer | php"
  when: composer_installed is failed

- name: upgrade composer
  become: yes
  shell: "cd {{ composer.dir }} && ./composer.phar self-update"
  when: composer_installed is success

- name: symlink composer in /usr/local/bin
  file: src="{{ composer.dir }}/composer.phar" dest=/usr/local/bin/{{ item }} state=link
  become: yes
  with_items:
    - composer
    - composer.phar

- name: add composer binary dir to path
  lineinfile: dest=~/.bashrc line='PATH=~/.composer/vendor/bin:$PATH'
