- set_fact: vhost_counter={{ vhost_counter | int + 1 }}

- name: install nginx
  apt: pkg=nginx state=latest
  become: yes

- name: create partials directory
  file: name=/etc/nginx/conf.d/partials state=directory
  become: yes

- include_vars: "{{ item }}"
  with_first_found:
   - "{{ ansible_distribution }}-php-{{ php_version_installed }}.yml"
   - "default-php-{{ php_version_installed | int }}.x.yml"
   - "default-php.yml"
  when: "php_version_installed is defined"

- name: install partials for php
  template: src=_php_fpm.conf dest=/etc/nginx/conf.d/partials/_php_fpm.conf
  become: yes
  when: "php_version_installed is defined"

- name: remove default vhost
  file: name=/etc/nginx/sites-{{ item }}/default state=absent
  become: yes
  with_items:
      - enabled
      - available
  notify: reload nginx

- name: create vhost config
  template: src={{ site_template }} dest=/etc/nginx/sites-available/{{ vhost }}
  become: yes

- name: enable vhost
  file: src=/etc/nginx/sites-available/{{ vhost }} dest=/etc/nginx/sites-enabled/{{ '%04d'|format(vhost_counter|int) }}-{{ vhost }} state=link
  become: yes
  notify: reload nginx

- name: make sure nginx starts at boot
  service: name=nginx enabled=yes
  become: yes
  notify: restart nginx

- meta: flush_handlers
