- name: install git and utilities
  apt:
    state: latest
    pkg:
      - git
      - libimage-exiftool-perl
  become: yes

- name: install default git config system wide
  copy:
    src: gitconfig
    dest: /etc/gitconfig
  become: yes

- name: install global ignore and attributes file
  copy:
    src: "{{ item }}"
    dest: "~/.{{ item }}"
  loop:
    - gitglobalignore
    - gitglobalattributes

- name: get git username from synced config
  shell: git config --file ~/.gitconfig-host user.name
  register: git_username
  ignore_errors: yes

- name: get git email from synced config
  shell: git config --file ~/.gitconfig-host user.email
  register: git_email
  ignore_errors: yes

- name: set box git username
  git_config:
    name: user.name
    value: "{{ git_username.stdout }}"
    scope: system
  become: yes

- name: set box git email
  git_config:
    name: user.email
    value: "{{ git_email.stdout }}"
    scope: system
  become: yes

- stat: path=/usr/local/bin/diff-so-fancy
  register: fancy_diff_file

- include: fancy-diff.yml
  when: fancy_diff and not (fancy_diff_file.stat.exists is defined and fancy_diff_file.stat.exists)

- name: install synced git config
  file:
    src: ~/.gitconfig-host
    dest: ~/.gitconfig
    state: link
    force: yes
  when: sync_git_with_host
