- name: restart supervisor
  shell: /etc/init.d/supervisor stop; /etc/init.d/supervisor start; exit 0
  become: yes

- name: start supervisor
  service: name=supervisor state=started
  become: yes

- name: stop supervisor
  service: name=supervisor state=stopped
  become: yes

- name: enable supervisor
  service: name=supervisor enabled=yes
  become: yes

- name: restart supervisor service
  command: supervisorctl restart {{ name }}
  become: yes
