---
dependencies:
  - { role: virtualenv, when: not django_use_pipenv }
  - { role: pipenv, when: django_use_pipenv }
  - { role: nginx, web_directory: "{{ django_root }}", site_template: "django-site.j2", proxy_port: 8000, when: "no_nginx is not defined" }
