- name: Download phantomjs
  get_url: url={{ phantomjs_url }} dest=/opt/phantomjs.tar.bz2
  become: yes

- name: Unpack phantomjs
  unarchive: src=/opt/phantomjs.tar.bz2 dest=/opt/ copy=no creates=/opt/{{ phantomjs_name }}/
  become: yes

- name: Create phantomjs Symlink
  file: state=link src=/opt/{{ phantomjs_name }}/bin/phantomjs path=/usr/local/bin/phantomjs
  become: yes
