- name: ensure rabbitmq is installed
  apt: pkg=rabbitmq-server state=present
  become: yes

- name: activate rabbitmq_management plugin
  shell: "/usr/sbin/rabbitmq-plugins enable rabbitmq_management"
  become: yes

- name: restart rabbitmq
  service: name=rabbitmq-server state=restarted
  become: yes

- name: get rabbitmqadmin script
  get_url: url=http://localhost:15672/cli/rabbitmqadmin dest=/usr/local/bin/rabbitmqadmin mode=755
  become: yes
